services:
  oxigit:
    image: ghcr.io/b-nova/oxigit:main
    ports:
      - "9100:9100"
      - "2222:2222"
    volumes:
      - oxigit-data:/app/data
    environment:
      - RUST_LOG=info

volumes:
  oxigit-data:
